FROM registry.access.redhat.com/rhel7
MAINTAINER Manabu Ori <ori@redhat.com>
ADD myreposync.rhel7 /myreposync
ADD aggregate.sh /aggregate.sh
ADD reposync.sh /reposync.sh
CMD ["/reposync.sh"]

# vim:et:
